# Generated by Django 5.1.6 on 2025-03-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happybondgin_web', '0002_alter_user_options_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='document_file',
            field=models.FileField(default=10, upload_to='user_documents/'),
            preserve_default=False,
        ),
    ]
